version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Wjx@Mhcjly04!
      MYSQL_DATABASE: company
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: employee_crud_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: release
    command: ["./employee-crud"]

volumes:
  db_data: