SERVER_PORT: ":8080"
MYSQL_DSN: "root:root_password@tcp(mysql:3306)/ecommerce?charset=utf8mb4&parseTime=True&loc=Local"
REDIS_ADDR: "redis:6379"
REDIS_PASSWORD: ""
REDIS_DB: 0
ES_ADDRESSES: "http://elasticsearch:9200"